engines:
  tslint:
    enabled: true
    channel: beta
    config: tslint.json
  fixme:
    enabled: true
ratings:
  paths:
  - "**.ts"
exclude_paths:
- node_modules
- "**.d.ts"
- "**.spec.ts"
- "**.demo.ts"
