engines:
  tslint:
    enabled: true
    channel: beta
   markdownlint:
     enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
ratings:
  paths:
  - src/**/*
  - examples/**/*
  - "**.md"x
exclude_paths:
- node_modules
