theme: jekyll-theme-cayman
url: "https://haleyhousellc.github.io"
baseurl: "/arboriculture"
repository: "haleyhousellc/arboriculture"
breadcrumbs: true
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      author_profile: true
      read_time: true
      sidebar:
        nav: "docs"
